version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/warframe-wiki"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "warframe-wiki-bot"
    reviewers:
      - "warframe-wiki-maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    ignore:
      # Ignore patch updates for stable dependencies
      - dependency-name: "urllib3"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "certifi"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    assignees:
      - "warframe-wiki-bot"
    reviewers:
      - "warframe-wiki-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 3

  # Docker (if we add Docker later)
  - package-ecosystem: "docker"
    directory: "/warframe-wiki"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    assignees:
      - "warframe-wiki-bot"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 2